### ISSUE TITLE
Screen goes white after WholeAnimateTime over

### ISSUE THREAD

**Issue by shanu95** [IamStY/SnowFalling#4]
Screen goes to white after whole animate time over. anyway to fix it?
![Screenshot_1576480424](https://user-images.githubusercontent.com/39364254/70889049-af87e480-2007-11ea-8f53-bd4c2296e1ec.png)

**Comment by IamStY** [comment]
try not to put view(s) inside the custom layout , since it calls removeAllViews when it calls stopSnowing()  , try making it individually on top of all views
![save](https://user-images.githubusercontent.com/14084447/74581978-fd619e80-4ff0-11ea-9255-395437829da0.png)
